[package]
name = "structural_macro"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = "0.13.1"
windows = { version = "0.58.0", features = [
  "Win32_System_SystemServices",
  "Win32_UI_WindowsAndMessaging",
] }
